[package]
name = "eure-blog"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"

[dependencies]
eure = { package = "eure", git = "https://github.com/Hihaheho/eure" }
indexmap = "2"
maud = "0.27.0"
markdown = "1"
giallo = { version = "0.2", features = ["dump"] }
